version: '3.7'
services:  
  nodejs:
    build: 
        context: .
        dockerfile: Dockerfile
    image: customerservice 
    tty: true
    volumes:
      - ./docs:/app/docs
      - ./node_modules:/app/node_modules
    ports:
      - "8080:8080"
    working_dir: /app
    
    command: redoc-cli bundle -o ./docs/index.html /app/specs/api.yml && ping localhost && redoc-cli serve /app/specs/api.yml